### ISSUE TITLE
Casting Error on 1.13+

### ISSUE THREAD

**Issue by Eptiiix** [Simplix-Softworks/Cirrus#2]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R1.inventory.CraftInventoryCustom$MinecraftInventory cannot be cast to net.minecraft.server.v1_16_R1.PlayerInventory
        at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftContainer.<init>(CraftContainer.java:51) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:396) ~[patched_1.16.1.jar:git-Paper-135]
        at dev.simplix.cirrus.spigot.menubuilder.SpigotMenuBuilder.open(SpigotMenuBuilder.java:158) ~[?:?]
        at dev.simplix.cirrus.common.menu.AbstractMenu.open(AbstractMenu.java:96) ~[?:?]
        at dev.simplix.cirrus.common.prefabs.menu.MultiPageMenu.open(MultiPageMenu.java:77) ~[?:?]
        at dev.simplix.cirrus.spigot.example.commands.TestCommand.execute(TestCommand.java:40) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-135]

**Comment by JavaFactoryDev** [comment]
Hi,
Cirrus is currently in early development. We will have a look later today.

Best,
Leonhard
SimplixSoftworks
